### ISSUE TITLE
OCR'ing the Numbo source code?  

### ISSUE THREAD

**Issue by Alex-Linhares** [Alex-Linhares/FARGonautica#10]
It would be wonderful if someone skilled on these things could OCR [Numbo's source code](/Software/Numbo/numbo.Daniel.Defays.1987.pdf).  If such a kind soul is out there, please let us have editable code that (might) be runnable soon!

**Comment by braxtonsherouse** [comment]
I just wanted to drop a quick note here to say that I've started on this, and am about halfway through.

My current plan is to end up with two versions:
 - one that's just a digitization of the source files, as they come
 - one that updates the source to using CLOS instead of Flavors, and therefore (hopefully) can run in more Common Lisp environments

@Alex-Linhares Does that seem reasonable to you? and, would you be willing to review this when it's ready?

**Comment by Alex-Linhares** [comment]
Yes, I think that would be awesome!

**Comment by braxtonsherouse** [comment]
I've finished up a first pass through, and have a [work-in-progress branch](https://github.com/braxtonsherouse/FARGonautica/tree/wip-add-numbo-source) you can check out. I'll do another pass, add a readme, etc., then open a pull request.

I'm less optimistic now about getting it up and running — the files in the printout aren't enough to reconstruct the program. It's hard to tell the extent of what's missing, but at the very least we're missing the coderack-specific code (`cr-hang`, `cr-choose`, etc.).

**Comment by Alex-Linhares** [comment]
That sounds incredible. I have Defays book, so I will take a look in there
and perhaps these can be reconstructed from there.

**Comment by Alex-Linhares** [comment]
Closing, thanks to braxtonsherouse.
